// Enhanced Medicine Database with 25+ medicines
export interface Medicine {
  id: number
  name: string
  genericName: string
  category: string
  price: number
  originalPrice: number
  rating: number
  reviews: number
  image: string
  prescription: boolean
  inStock: boolean
  manufacturer: string
  description: string
  activeIngredient: string
  strength: string
  form: string
  uses: string[]
  sideEffects: string[]
  precautions: string[]
  dosage: string
}

export const medicineDatabase: Medicine[] = [
  {
    id: 1,
    name: "Paracetamol 500mg",
    genericName: "Paracetamol",
    category: "Pain Relief",
    price: 45,
    originalPrice: 60,
    rating: 4.5,
    reviews: 234,
    image: "/placeholder.svg?height=200&width=200&text=Paracetamol",
    prescription: false,
    inStock: true,
    manufacturer: "GlaxoSmithKline",
    description: "Effective pain relief and fever reducer",
    activeIngredient: "Paracetamol",
    strength: "500mg",
    form: "Tablet",
    uses: ["Pain relief", "Fever reduction", "Headache", "Body ache"],
    sideEffects: ["Rare: Skin rash", "Nausea (uncommon)"],
    precautions: ["Do not exceed 8 tablets in 24 hours", "Avoid alcohol", "Consult doctor if symptoms persist"],
    dosage: "Adults: 1-2 tablets every 4-6 hours",
  },
  {
    id: 2,
    name: "Cetirizine 10mg",
    genericName: "Cetirizine",
    category: "Allergy",
    price: 85,
    originalPrice: 100,
    rating: 4.3,
    reviews: 156,
    image: "/placeholder.svg?height=200&width=200&text=Cetirizine",
    prescription: false,
    inStock: true,
    manufacturer: "Cipla",
    description: "Antihistamine for allergic reactions",
    activeIngredient: "Cetirizine Hydrochloride",
    strength: "10mg",
    form: "Tablet",
    uses: ["Allergic rhinitis", "Urticaria", "Hay fever", "Skin allergies"],
    sideEffects: ["Drowsiness", "Dry mouth", "Fatigue"],
    precautions: ["May cause drowsiness", "Avoid alcohol", "Use caution when driving"],
    dosage: "Adults: 1 tablet once daily",
  },
  {
    id: 3,
    name: "Vitamin D3 60000 IU",
    genericName: "Cholecalciferol",
    category: "Supplements",
    price: 320,
    originalPrice: 400,
    rating: 4.7,
    reviews: 89,
    image: "/placeholder.svg?height=200&width=200&text=VitaminD3",
    prescription: false,
    inStock: true,
    manufacturer: "Sun Pharma",
    description: "Essential vitamin D supplement",
    activeIngredient: "Cholecalciferol",
    strength: "60000 IU",
    form: "Capsule",
    uses: ["Bone health", "Immune support", "Calcium absorption", "Vitamin D deficiency"],
    sideEffects: ["Nausea", "Vomiting", "Weakness"],
    precautions: ["Monitor calcium levels", "Do not exceed recommended dose"],
    dosage: "1 capsule weekly or as directed",
  },
  {
    id: 4,
    name: "Omeprazole 20mg",
    genericName: "Omeprazole",
    category: "Digestive Health",
    price: 125,
    originalPrice: 150,
    rating: 4.4,
    reviews: 67,
    image: "/placeholder.svg?height=200&width=200&text=Omeprazole",
    prescription: true,
    inStock: true,
    manufacturer: "Dr. Reddy's",
    description: "Proton pump inhibitor for acid reflux",
    activeIngredient: "Omeprazole",
    strength: "20mg",
    form: "Capsule",
    uses: ["GERD", "Peptic ulcers", "Acid reflux", "Heartburn"],
    sideEffects: ["Headache", "Nausea", "Diarrhea"],
    precautions: ["Take on empty stomach", "May interact with other medications"],
    dosage: "1 capsule once daily before breakfast",
  },
  {
    id: 5,
    name: "Ibuprofen 400mg",
    genericName: "Ibuprofen",
    category: "Pain Relief",
    price: 65,
    originalPrice: 80,
    rating: 4.2,
    reviews: 198,
    image: "/placeholder.svg?height=200&width=200&text=Ibuprofen",
    prescription: false,
    inStock: true,
    manufacturer: "Abbott",
    description: "Anti-inflammatory pain reliever",
    activeIngredient: "Ibuprofen",
    strength: "400mg",
    form: "Tablet",
    uses: ["Pain relief", "Inflammation", "Fever", "Arthritis"],
    sideEffects: ["Stomach upset", "Nausea", "Dizziness"],
    precautions: ["Take with food", "Avoid if stomach ulcers", "Monitor blood pressure"],
    dosage: "1 tablet every 6-8 hours with food",
  },
  {
    id: 6,
    name: "Multivitamin Tablets",
    genericName: "Multivitamin",
    category: "Supplements",
    price: 299,
    originalPrice: 399,
    rating: 4.6,
    reviews: 145,
    image: "/placeholder.svg?height=200&width=200&text=Multivitamin",
    prescription: false,
    inStock: false,
    manufacturer: "Himalaya",
    description: "Complete multivitamin formula",
    activeIngredient: "Multiple vitamins and minerals",
    strength: "Various",
    form: "Tablet",
    uses: ["Nutritional support", "Energy boost", "Immune support", "Overall health"],
    sideEffects: ["Mild stomach upset", "Nausea"],
    precautions: ["Take with food", "Do not exceed recommended dose"],
    dosage: "1 tablet daily with breakfast",
  },
  {
    id: 7,
    name: "Amoxicillin 250mg",
    genericName: "Amoxicillin",
    category: "Antibiotics",
    price: 125,
    originalPrice: 150,
    rating: 4.3,
    reviews: 89,
    image: "/placeholder.svg?height=200&width=200&text=Amoxicillin",
    prescription: true,
    inStock: true,
    manufacturer: "Cipla",
    description: "Broad-spectrum antibiotic",
    activeIngredient: "Amoxicillin",
    strength: "250mg",
    form: "Capsule",
    uses: ["Bacterial infections", "Respiratory infections", "UTI", "Skin infections"],
    sideEffects: ["Nausea", "Diarrhea", "Allergic reactions"],
    precautions: ["Complete full course", "Take with food", "Avoid if allergic to penicillin"],
    dosage: "1 capsule 3 times daily for 7-10 days",
  },
  {
    id: 8,
    name: "Metformin 500mg",
    genericName: "Metformin",
    category: "Diabetes",
    price: 85,
    originalPrice: 110,
    rating: 4.4,
    reviews: 156,
    image: "/placeholder.svg?height=200&width=200&text=Metformin",
    prescription: true,
    inStock: true,
    manufacturer: "Sun Pharma",
    description: "Type 2 diabetes medication",
    activeIngredient: "Metformin Hydrochloride",
    strength: "500mg",
    form: "Tablet",
    uses: ["Type 2 diabetes", "Blood sugar control", "PCOS"],
    sideEffects: ["Nausea", "Diarrhea", "Metallic taste"],
    precautions: ["Take with meals", "Monitor kidney function", "Avoid alcohol"],
    dosage: "1-2 tablets twice daily with meals",
  },
  {
    id: 9,
    name: "Amlodipine 5mg",
    genericName: "Amlodipine",
    category: "Cardiovascular",
    price: 95,
    originalPrice: 120,
    rating: 4.2,
    reviews: 78,
    image: "/placeholder.svg?height=200&width=200&text=Amlodipine",
    prescription: true,
    inStock: true,
    manufacturer: "Pfizer",
    description: "Calcium channel blocker for hypertension",
    activeIngredient: "Amlodipine Besylate",
    strength: "5mg",
    form: "Tablet",
    uses: ["High blood pressure", "Angina", "Coronary artery disease"],
    sideEffects: ["Ankle swelling", "Flushing", "Palpitations"],
    precautions: ["Monitor blood pressure", "Avoid grapefruit juice"],
    dosage: "1 tablet once daily",
  },
  {
    id: 10,
    name: "Loratadine 10mg",
    genericName: "Loratadine",
    category: "Allergy",
    price: 75,
    originalPrice: 95,
    rating: 4.1,
    reviews: 134,
    image: "/placeholder.svg?height=200&width=200&text=Loratadine",
    prescription: false,
    inStock: true,
    manufacturer: "Johnson & Johnson",
    description: "Non-drowsy antihistamine",
    activeIngredient: "Loratadine",
    strength: "10mg",
    form: "Tablet",
    uses: ["Seasonal allergies", "Hay fever", "Hives", "Allergic rhinitis"],
    sideEffects: ["Headache", "Dry mouth", "Fatigue"],
    precautions: ["Less drowsy than other antihistamines", "Avoid alcohol"],
    dosage: "1 tablet once daily",
  },
  {
    id: 11,
    name: "Azithromycin 250mg",
    genericName: "Azithromycin",
    category: "Antibiotics",
    price: 145,
    originalPrice: 180,
    rating: 4.5,
    reviews: 92,
    image: "/placeholder.svg?height=200&width=200&text=Azithromycin",
    prescription: true,
    inStock: true,
    manufacturer: "Pfizer",
    description: "Macrolide antibiotic",
    activeIngredient: "Azithromycin",
    strength: "250mg",
    form: "Tablet",
    uses: ["Respiratory infections", "Skin infections", "STDs", "Pneumonia"],
    sideEffects: ["Nausea", "Diarrhea", "Abdominal pain"],
    precautions: ["Complete full course", "May interact with other medications"],
    dosage: "1 tablet once daily for 3-5 days",
  },
  {
    id: 12,
    name: "Calcium Carbonate 500mg",
    genericName: "Calcium Carbonate",
    category: "Supplements",
    price: 55,
    originalPrice: 75,
    rating: 4.3,
    reviews: 167,
    image: "/placeholder.svg?height=200&width=200&text=Calcium",
    prescription: false,
    inStock: true,
    manufacturer: "Abbott",
    description: "Calcium supplement for bone health",
    activeIngredient: "Calcium Carbonate",
    strength: "500mg",
    form: "Tablet",
    uses: ["Bone health", "Calcium deficiency", "Osteoporosis prevention"],
    sideEffects: ["Constipation", "Gas", "Bloating"],
    precautions: ["Take with food", "Drink plenty of water"],
    dosage: "1-2 tablets daily with meals",
  },
  {
    id: 13,
    name: "Diclofenac 50mg",
    genericName: "Diclofenac",
    category: "Pain Relief",
    price: 85,
    originalPrice: 105,
    rating: 4.0,
    reviews: 123,
    image: "/placeholder.svg?height=200&width=200&text=Diclofenac",
    prescription: true,
    inStock: true,
    manufacturer: "Novartis",
    description: "NSAID for pain and inflammation",
    activeIngredient: "Diclofenac Sodium",
    strength: "50mg",
    form: "Tablet",
    uses: ["Arthritis", "Joint pain", "Muscle pain", "Inflammation"],
    sideEffects: ["Stomach upset", "Nausea", "Dizziness"],
    precautions: ["Take with food", "Monitor kidney function", "Avoid if stomach ulcers"],
    dosage: "1 tablet 2-3 times daily with food",
  },
  {
    id: 14,
    name: "Ranitidine 150mg",
    genericName: "Ranitidine",
    category: "Digestive Health",
    price: 65,
    originalPrice: 85,
    rating: 4.2,
    reviews: 98,
    image: "/placeholder.svg?height=200&width=200&text=Ranitidine",
    prescription: false,
    inStock: true,
    manufacturer: "GSK",
    description: "H2 receptor antagonist for acid reduction",
    activeIngredient: "Ranitidine Hydrochloride",
    strength: "150mg",
    form: "Tablet",
    uses: ["Heartburn", "Acid indigestion", "Peptic ulcers", "GERD"],
    sideEffects: ["Headache", "Dizziness", "Constipation"],
    precautions: ["Take before meals", "Avoid alcohol"],
    dosage: "1 tablet twice daily",
  },
  {
    id: 15,
    name: "Iron Tablets 65mg",
    genericName: "Ferrous Sulfate",
    category: "Supplements",
    price: 45,
    originalPrice: 60,
    rating: 4.1,
    reviews: 145,
    image: "/placeholder.svg?height=200&width=200&text=Iron",
    prescription: false,
    inStock: true,
    manufacturer: "Himalaya",
    description: "Iron supplement for anemia",
    activeIngredient: "Ferrous Sulfate",
    strength: "65mg",
    form: "Tablet",
    uses: ["Iron deficiency anemia", "Low iron levels", "Pregnancy support"],
    sideEffects: ["Constipation", "Nausea", "Dark stools"],
    precautions: ["Take on empty stomach", "Avoid tea/coffee", "May cause constipation"],
    dosage: "1 tablet daily or as directed",
  },
  {
    id: 16,
    name: "Aspirin 75mg",
    genericName: "Aspirin",
    category: "Cardiovascular",
    price: 35,
    originalPrice: 50,
    rating: 4.4,
    reviews: 189,
    image: "/placeholder.svg?height=200&width=200&text=Aspirin",
    prescription: false,
    inStock: true,
    manufacturer: "Bayer",
    description: "Low-dose aspirin for heart protection",
    activeIngredient: "Acetylsalicylic Acid",
    strength: "75mg",
    form: "Tablet",
    uses: ["Heart attack prevention", "Stroke prevention", "Blood clot prevention"],
    sideEffects: ["Stomach irritation", "Bleeding risk", "Nausea"],
    precautions: ["Take with food", "Monitor for bleeding", "Avoid if allergic"],
    dosage: "1 tablet once daily with food",
  },
  {
    id: 17,
    name: "Montelukast 10mg",
    genericName: "Montelukast",
    category: "Respiratory",
    price: 165,
    originalPrice: 200,
    rating: 4.3,
    reviews: 76,
    image: "/placeholder.svg?height=200&width=200&text=Montelukast",
    prescription: true,
    inStock: true,
    manufacturer: "Merck",
    description: "Leukotriene receptor antagonist for asthma",
    activeIngredient: "Montelukast Sodium",
    strength: "10mg",
    form: "Tablet",
    uses: ["Asthma", "Allergic rhinitis", "Exercise-induced bronchospasm"],
    sideEffects: ["Headache", "Dizziness", "Stomach pain"],
    precautions: ["Take in evening", "Monitor mood changes"],
    dosage: "1 tablet once daily in the evening",
  },
  {
    id: 18,
    name: "Pantoprazole 40mg",
    genericName: "Pantoprazole",
    category: "Digestive Health",
    price: 135,
    originalPrice: 165,
    rating: 4.5,
    reviews: 112,
    image: "/placeholder.svg?height=200&width=200&text=Pantoprazole",
    prescription: true,
    inStock: true,
    manufacturer: "Sun Pharma",
    description: "Proton pump inhibitor",
    activeIngredient: "Pantoprazole Sodium",
    strength: "40mg",
    form: "Tablet",
    uses: ["GERD", "Peptic ulcers", "Zollinger-Ellison syndrome"],
    sideEffects: ["Headache", "Diarrhea", "Nausea"],
    precautions: ["Take before meals", "May affect magnesium levels"],
    dosage: "1 tablet once daily before breakfast",
  },
  {
    id: 19,
    name: "Folic Acid 5mg",
    genericName: "Folic Acid",
    category: "Supplements",
    price: 25,
    originalPrice: 35,
    rating: 4.6,
    reviews: 203,
    image: "/placeholder.svg?height=200&width=200&text=FolicAcid",
    prescription: false,
    inStock: true,
    manufacturer: "Abbott",
    description: "Essential B vitamin supplement",
    activeIngredient: "Folic Acid",
    strength: "5mg",
    form: "Tablet",
    uses: ["Pregnancy support", "Anemia prevention", "Neural tube defects prevention"],
    sideEffects: ["Rare: Allergic reactions", "Nausea"],
    precautions: ["Important during pregnancy", "Take as directed"],
    dosage: "1 tablet daily or as directed",
  },
  {
    id: 20,
    name: "Salbutamol Inhaler",
    genericName: "Salbutamol",
    category: "Respiratory",
    price: 185,
    originalPrice: 220,
    rating: 4.7,
    reviews: 134,
    image: "/placeholder.svg?height=200&width=200&text=Salbutamol",
    prescription: true,
    inStock: true,
    manufacturer: "GSK",
    description: "Bronchodilator inhaler for asthma",
    activeIngredient: "Salbutamol Sulfate",
    strength: "100mcg/dose",
    form: "Inhaler",
    uses: ["Asthma", "COPD", "Bronchospasm", "Wheezing"],
    sideEffects: ["Tremor", "Palpitations", "Headache"],
    precautions: ["Shake before use", "Rinse mouth after use"],
    dosage: "1-2 puffs as needed, max 8 puffs daily",
  },
  {
    id: 21,
    name: "Levothyroxine 50mcg",
    genericName: "Levothyroxine",
    category: "Hormonal",
    price: 95,
    originalPrice: 125,
    rating: 4.4,
    reviews: 87,
    image: "/placeholder.svg?height=200&width=200&text=Levothyroxine",
    prescription: true,
    inStock: true,
    manufacturer: "Abbott",
    description: "Thyroid hormone replacement",
    activeIngredient: "Levothyroxine Sodium",
    strength: "50mcg",
    form: "Tablet",
    uses: ["Hypothyroidism", "Thyroid hormone deficiency", "Goiter"],
    sideEffects: ["Palpitations", "Insomnia", "Weight loss"],
    precautions: ["Take on empty stomach", "Regular monitoring required"],
    dosage: "1 tablet once daily on empty stomach",
  },
  {
    id: 22,
    name: "Cough Syrup 100ml",
    genericName: "Dextromethorphan",
    category: "Cold & Flu",
    price: 75,
    originalPrice: 95,
    rating: 4.2,
    reviews: 156,
    image: "/placeholder.svg?height=200&width=200&text=CoughSyrup",
    prescription: false,
    inStock: true,
    manufacturer: "Pfizer",
    description: "Cough suppressant syrup",
    activeIngredient: "Dextromethorphan HBr",
    strength: "15mg/5ml",
    form: "Syrup",
    uses: ["Dry cough", "Throat irritation", "Cold symptoms"],
    sideEffects: ["Drowsiness", "Dizziness", "Nausea"],
    precautions: ["Do not exceed recommended dose", "Avoid alcohol"],
    dosage: "10ml every 4-6 hours, max 60ml daily",
  },
  {
    id: 23,
    name: "Zinc Tablets 50mg",
    genericName: "Zinc Sulfate",
    category: "Supplements",
    price: 65,
    originalPrice: 85,
    rating: 4.3,
    reviews: 98,
    image: "/placeholder.svg?height=200&width=200&text=Zinc",
    prescription: false,
    inStock: true,
    manufacturer: "Himalaya",
    description: "Zinc supplement for immune support",
    activeIngredient: "Zinc Sulfate",
    strength: "50mg",
    form: "Tablet",
    uses: ["Immune support", "Wound healing", "Zinc deficiency"],
    sideEffects: ["Nausea", "Stomach upset", "Metallic taste"],
    precautions: ["Take with food", "Do not exceed recommended dose"],
    dosage: "1 tablet daily with food",
  },
  {
    id: 24,
    name: "Antibiotic Eye Drops",
    genericName: "Chloramphenicol",
    category: "Eye Care",
    price: 85,
    originalPrice: 110,
    rating: 4.1,
    reviews: 67,
    image: "/placeholder.svg?height=200&width=200&text=EyeDrops",
    prescription: true,
    inStock: true,
    manufacturer: "Allergan",
    description: "Antibiotic eye drops for infections",
    activeIngredient: "Chloramphenicol",
    strength: "0.5%",
    form: "Eye Drops",
    uses: ["Bacterial eye infections", "Conjunctivitis", "Eye inflammation"],
    sideEffects: ["Eye irritation", "Burning sensation", "Blurred vision"],
    precautions: ["For external use only", "Complete full course"],
    dosage: "1-2 drops every 2-4 hours",
  },
  {
    id: 25,
    name: "Antacid Tablets",
    genericName: "Aluminum Hydroxide",
    category: "Digestive Health",
    price: 45,
    originalPrice: 60,
    rating: 4.0,
    reviews: 178,
    image: "/placeholder.svg?height=200&width=200&text=Antacid",
    prescription: false,
    inStock: true,
    manufacturer: "Johnson & Johnson",
    description: "Fast-acting antacid for heartburn",
    activeIngredient: "Aluminum Hydroxide + Magnesium Hydroxide",
    strength: "400mg + 400mg",
    form: "Chewable Tablet",
    uses: ["Heartburn", "Acid indigestion", "Stomach upset", "Gas"],
    sideEffects: ["Constipation", "Diarrhea", "Chalky taste"],
    precautions: ["Chew thoroughly", "Do not exceed 12 tablets daily"],
    dosage: "2-4 tablets as needed after meals",
  },
]

// Category mappings for better organization
export const categoryMappings = {
  "pain-relief": "Pain Relief",
  "cold-flu": "Cold & Flu",
  vitamins: "Supplements",
  "skin-care": "Skin Care",
  "baby-care": "Baby Care",
  diabetes: "Diabetes",
  allergy: "Allergy",
  "digestive-health": "Digestive Health",
  antibiotics: "Antibiotics",
  cardiovascular: "Cardiovascular",
  respiratory: "Respiratory",
  hormonal: "Hormonal",
  "eye-care": "Eye Care",
}

// Search function
export function searchMedicines(query: string, category?: string): Medicine[] {
  let results = medicineDatabase

  // Filter by category if specified
  if (category && category !== "all") {
    const categoryName = categoryMappings[category as keyof typeof categoryMappings] || category
    results = results.filter((medicine) => medicine.category === categoryName)
  }

  // Filter by search query
  if (query.trim()) {
    const searchTerm = query.toLowerCase()
    results = results.filter(
      (medicine) =>
        medicine.name.toLowerCase().includes(searchTerm) ||
        medicine.genericName.toLowerCase().includes(searchTerm) ||
        medicine.manufacturer.toLowerCase().includes(searchTerm) ||
        medicine.description.toLowerCase().includes(searchTerm) ||
        medicine.activeIngredient.toLowerCase().includes(searchTerm) ||
        medicine.uses.some((use) => use.toLowerCase().includes(searchTerm)),
    )
  }

  return results
}

// Get medicine by ID
export function getMedicineById(id: number): Medicine | undefined {
  return medicineDatabase.find((medicine) => medicine.id === id)
}

// Get medicines by category
export function getMedicinesByCategory(category: string): Medicine[] {
  const categoryName = categoryMappings[category as keyof typeof categoryMappings] || category
  return medicineDatabase.filter((medicine) => medicine.category === categoryName)
}

// Get all categories
export function getAllCategories(): string[] {
  return [...new Set(medicineDatabase.map((medicine) => medicine.category))]
}

// Get featured medicines
export function getFeaturedMedicines(limit = 8): Medicine[] {
  return medicineDatabase
    .filter((medicine) => medicine.inStock)
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit)
}
